### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lud** [myskoach/sublime-ex-formatter#2]
Hi, 

I just submitted an issue in the old repo about the cursor jumping to the wrong line in case of compilation errors (it reads the column number from the error, and not the line number).

I then saw that a pull request was made, and that this repo was born. Now my real question is : As I install through package control, when I search for `ElixirFormatter`, how do I know that _this_ package is installed, and not the one in the unmaintained repository? As both readme files declare the same name.

Thank you.

**Comment by lud** [comment]
Ok so I found in the Package Control website that this is the repo corresponding to the package.

**Comment by jmnsf** [comment]
@lud just as a clarification for this, we [took over](https://github.com/wbond/package_control_channel/pull/8194) the package name, since the original was defunct.

**Comment by lud** [comment]
That is what I supposed, thank you for making it clear!
