### ISSUE TITLE
Wrong line number on errors

### ISSUE THREAD

**Issue by lud** [myskoach/sublime-ex-formatter#3]
The Elixir compiler errors will show errors like this:

```
** (SyntaxError) lib/myapp/myfile.ex:68:41: syntax error before: '}'
```

In ST, the cursor will jump to line `41` but it should jump to line `68` as `41` is the column.

Edit: Btw, thank you so much for the improvements on this package !

**Comment by jmnsf** [comment]
Hah, interesting. Thanks for the report, will have a look 👍

**Comment by lud** [comment]
Maybe you do not have the same behaviour because of your elixir version. Mine is `Elixir 1.11.3 (compiled with Erlang/OTP 23)` installed with homebrew/MacOS Mojave.

**Comment by lud** [comment]
Oh and the status bar in ST show the column number too, so I guess it's just an error during the parse.

**Comment by lud** [comment]
I guess the following

```
SYNTAX_ERROR_RE = re.compile(
    r"^\*\*\s\((.+)\)\s(.+)\:(\d+)\:\s(.+)$",
    re.MULTILINE | re.IGNORECASE | re.UNICODE)
```

should be replaced with

```
SYNTAX_ERROR_RE = re.compile(
    r"^\*\*\s\((.+)\)\s([^:]+)\:(\d+)\:(\d+)\:\s(.+)$",
    re.MULTILINE | re.IGNORECASE | re.UNICODE)
```

But I cannot test, I don't know where the file is.

**Comment by jmnsf** [comment]
@lud You were on the money RE elixir version, thanks for the rec 👍

**Comment by lud** [comment]
Happy to help @jmnsf :)
